# -*- coding: utf-8 -*-
"""Cbr_visualisation_indexes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W-bfLpKciO89Pksd0bFBXyEQX5IFVrqv
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import numpy as np
import json
import re
import os

os.makedirs("figures", exist_ok=True)

# Load labeled data
OUTPUT_JSON = "cbr_labeled_predictions.json"

with open(OUTPUT_JSON, "r", encoding="utf-8") as f:
    labeled_data = json.load(f)

print(f"Loaded {len(labeled_data)} documents")

# Date parsing utilities
def parse_date_unified(published_at):
    """Parse date from various formats: '13 февраля 2026 г' or '20.03.2026'"""
    if not published_at:
        return None

    months_ru = {
        'января': 1, 'февраля': 2, 'марта': 3, 'апреля': 4,
        'мая': 5, 'июня': 6, 'июля': 7, 'августа': 8,
        'сентября': 9, 'октября': 10, 'ноября': 11, 'декабря': 12
    }

    try:
        # Format: '13 февраля 2026 г'
        match = re.search(r'(\d+)\s+(\w+)\s+(\d{4})', published_at)
        if match:
            day, month_name, year = match.groups()
            month = months_ru.get(month_name.lower())
            if month:
                return f"{year}-{month:02d}-{int(day):02d}"

        # Format: '20.03.2026' or '20-03-2026'
        match = re.search(r'(\d{2})[.\-/](\d{2})[.\-/](\d{4})', published_at)
        if match:
            day, month, year = match.groups()
            return f"{year}-{int(month):02d}-{int(day):02d}"

        # Format: '2026.03.20'
        match = re.search(r'(\d{4})[.\-/](\d{2})[.\-/](\d{2})', published_at)
        if match:
            year, month, day = match.groups()
            return f"{year}-{int(month):02d}-{int(day):02d}"

    except Exception as e:
        print(f"Date parsing error '{published_at}': {e}")
        return None

    return None

# Normalize dates
fixed_count = 0
for doc in labeled_data:
    if not doc.get("published_date"):
        published_at = doc.get("published_at", "")
        parsed_date = parse_date_unified(published_at)

        if parsed_date:
            doc["published_date"] = parsed_date
            fixed_count += 1

print(f"Fixed dates: {fixed_count}")
print(f"Documents with valid date: {sum(1 for d in labeled_data if d.get('published_date'))}")
print(f"Documents without date: {sum(1 for d in labeled_data if not d.get('published_date'))}")

# Prepare data for analysis
rows = []

for doc in labeled_data:
    if not doc.get("published_date"):
        continue

    total = doc["aggregated"]["total_sentences"]

    # Count shares (excluding Other)
    topic_counts = {k: v for k, v in doc["aggregated"]["topic_counts"].items() if k != "Other"}
    stance_counts = {k: v for k, v in doc["aggregated"]["stance_counts"].items() if k != "Other"}
    sentiment_counts = {k: v for k, v in doc["aggregated"]["sentiment_counts"].items() if k != "Other"}

    # Forward-lookingness score
    forward_count = stance_counts.get("forward-looking", 0)
    backward_count = stance_counts.get("backward-looking", 0)
    forward_lookingness = forward_count / (forward_count + backward_count) if (forward_count + backward_count) > 0 else 0

    row = {
        "doc_id": doc["doc_id"],
        "section": doc["section"],
        "category": doc["category"],
        "published_date": doc["published_date"],
        "year": int(doc["published_date"][:4]),
        "total_sentences": total,
        "forward_lookingness": forward_lookingness,
    }

    # Add topic shares
    for topic, count in topic_counts.items():
        row[f"topic_{topic}"] = count / total

    # Add stance shares
    for stance, count in stance_counts.items():
        row[f"stance_{stance}"] = count / total

    # Add sentiment shares
    for sentiment, count in sentiment_counts.items():
        row[f"sentiment_{sentiment}"] = count / total

    rows.append(row)

df = pd.DataFrame(rows)
df["published_date"] = pd.to_datetime(df["published_date"])
df = df.sort_values("published_date")

# Create semiannual periods
df["year_half"] = df["published_date"].dt.year.astype(str) + "-H" + ((df["published_date"].dt.month - 1) // 6 + 1).astype(str)

print(f"Prepared {len(df)} documents for analysis")
print(f"Period: {df['published_date'].min()} - {df['published_date'].max()}")
print(f"Document sections: {df['section'].unique()}")

# Topic distribution visualization
topic_cols = [col for col in df.columns if col.startswith("topic_") and "Other" not in col]
categories = ["summary", "statement", "press_release"]
df_filtered = df[df["category"].isin(categories)].copy()

# Fixed colors for consistency
colors = plt.cm.tab20(np.linspace(0, 1, len(topic_cols)))

def plot_topic_area(data, title, filename, topic_cols, colors):
    """Plot stacked area chart for topic distribution"""
    data = data.copy()
    data[topic_cols] = data[topic_cols].fillna(0)

    fig, ax = plt.subplots(figsize=(14, 6))

    x = np.arange(len(data))
    bottom = np.zeros(len(data))

    for i, col in enumerate(topic_cols):
        values = data[col].values
        ax.fill_between(x, bottom, bottom + values, label=col.replace("topic_", ""), alpha=0.75, color=colors[i])
        bottom += values

    step = max(1, len(x) // 10)
    ax.set_xticks(x[::step])
    ax.set_xticklabels(data["year_half"].values[::step], rotation=45, ha="right")

    ax.set_title(title, fontsize=14, fontweight="bold")
    ax.set_xlabel("Period (semiannual)", fontsize=12)
    ax.set_ylabel("Share of sentences", fontsize=12)
    ax.grid(True, alpha=0.3)
    ax.legend(bbox_to_anchor=(1.02, 1), loc="upper left", fontsize=9, frameon=True)

    plt.tight_layout()
    plt.savefig(filename, dpi=300, bbox_inches="tight")
    print(f"Saved: {filename}")
    plt.show()
    plt.close(fig)

# Overall topic distribution
topic_evolution_overall = df_filtered.groupby("year_half")[topic_cols].mean().reset_index()
plot_topic_area(topic_evolution_overall, "Topic Distribution: Overall", "figures/topic_distribution_overall.png", topic_cols, colors)

# Topic distribution by document type
for category in categories:
    cat_data = df_filtered[df_filtered["category"] == category].groupby("year_half")[topic_cols].mean().reset_index()
    plot_topic_area(cat_data, f"Topic Distribution: {category.replace('_', ' ').title()}", f"figures/topic_distribution_{category}.png", topic_cols, colors)

# Stance distribution visualization
stance_cols = [col for col in df.columns if col.startswith("stance_") and "Other" not in col]

# Fixed stance colors
default_stance_colors = {
    "Forward-looking": "#3498db",
    "Backward-looking": "#e74c3c",
    "forward-looking": "#3498db",
    "backward-looking": "#e74c3c",
}

colors = []
fallback = plt.cm.Set2(np.linspace(0, 1, len(stance_cols)))
for i, col in enumerate(stance_cols):
    label = col.replace("stance_", "")
    colors.append(default_stance_colors.get(label, fallback[i]))

def plot_stance_area(data, title, filename, stance_cols, colors):
    """Plot stacked area chart for stance distribution"""
    data = data.copy()
    data[stance_cols] = data[stance_cols].fillna(0)

    fig, ax = plt.subplots(figsize=(14, 6))

    x = np.arange(len(data))
    bottom = np.zeros(len(data))

    for i, col in enumerate(stance_cols):
        values = data[col].values
        ax.fill_between(x, bottom, bottom + values, label=col.replace("stance_", ""), alpha=0.75, color=colors[i])
        bottom += values

    step = max(1, len(x) // 10)
    ax.set_xticks(x[::step])
    ax.set_xticklabels(data["year_half"].values[::step], rotation=45, ha="right")

    ax.set_title(title, fontsize=14, fontweight="bold")
    ax.set_xlabel("Period (semiannual)", fontsize=12)
    ax.set_ylabel("Share of sentences", fontsize=12)
    ax.grid(True, alpha=0.3)
    ax.legend(loc="upper right", fontsize=10, frameon=True)

    plt.tight_layout()
    plt.savefig(filename, dpi=300, bbox_inches="tight")
    print(f"Saved: {filename}")
    plt.show()
    plt.close(fig)

# Overall stance distribution
stance_evolution_overall = df_filtered.groupby("year_half")[stance_cols].mean().reset_index()
plot_stance_area(stance_evolution_overall, "Stance Distribution: Overall", "figures/stance_distribution_overall.png", stance_cols, colors)

# Stance distribution by document type
for category in categories:
    cat_data = df_filtered[df_filtered["category"] == category].groupby("year_half")[stance_cols].mean().reset_index()
    plot_stance_area(cat_data, f"Stance Distribution: {category.replace('_', ' ').title()}", f"figures/stance_distribution_{category}.png", stance_cols, colors)

# Sentiment distribution visualization
sentiment_cols = [col for col in df.columns if col.startswith("sentiment_") and "Other" not in col]

# Fixed sentiment colors
color_map = {
    'sentiment_hawkish': '#e74c3c',
    'sentiment_dovish': '#3498db',
    'sentiment_neutral': '#95a5a6',
    'sentiment_risk-highlighting': '#e67e22',
    'sentiment_confidence-building': '#2ecc71',
}

fallback = plt.cm.Set2(np.linspace(0, 1, len(sentiment_cols)))
colors = [color_map.get(col, fallback[i]) for i, col in enumerate(sentiment_cols)]

def plot_sentiment_area(data, title, filename):
    """Plot stacked area chart for sentiment distribution"""
    data = data.copy()
    data[sentiment_cols] = data[sentiment_cols].fillna(0)

    fig, ax = plt.subplots(figsize=(14, 6))

    x = np.arange(len(data))
    bottom = np.zeros(len(data))

    for i, col in enumerate(sentiment_cols):
        values = data[col].values
        ax.fill_between(x, bottom, bottom + values, label=col.replace("sentiment_", ""), alpha=0.75, color=colors[i])
        bottom += values

    step = max(1, len(x) // 10)
    ax.set_xticks(x[::step])
    ax.set_xticklabels(data["year_half"].values[::step], rotation=45, ha="right")

    ax.set_title(title, fontsize=14, fontweight="bold")
    ax.set_xlabel("Period (semiannual)", fontsize=12)
    ax.set_ylabel("Share of sentences", fontsize=12)
    ax.grid(True, alpha=0.3)
    ax.legend(loc="upper right", fontsize=10, frameon=True)

    plt.tight_layout()
    plt.savefig(filename, dpi=300, bbox_inches="tight")
    print(f"Saved: {filename}")
    plt.show()
    plt.close(fig)

# Overall sentiment distribution
sentiment_overall = df_filtered.groupby("year_half")[sentiment_cols].mean().reset_index()
plot_sentiment_area(sentiment_overall, "Sentiment Distribution: Overall", "figures/sentiment_distribution_overall.png")

# Sentiment distribution by document type
for category in categories:
    cat_data = df_filtered[df_filtered["category"] == category].groupby("year_half")[sentiment_cols].mean().reset_index()
    plot_sentiment_area(cat_data, f"Sentiment Distribution: {category.replace('_', ' ').title()}", f"figures/sentiment_distribution_{category}.png")

# Communication indices calculation
sentiment_cols = [col for col in df.columns if col.startswith("sentiment_") and "Other" not in col]

# Document-level aggregation
doc_level = df.groupby("doc_id")[sentiment_cols].sum().reset_index()
doc_level["H"] = doc_level["sentiment_hawkish"]
doc_level["D"] = doc_level["sentiment_dovish"]
doc_level["N"] = doc_level["sentiment_neutral"]
doc_level["R"] = doc_level["sentiment_risk-highlighting"]
doc_level["C"] = doc_level["sentiment_confidence-building"]
eps = 1e-8

# Net Policy Stance
doc_level["NPS"] = (doc_level["H"] - doc_level["D"]) / (doc_level["H"] + doc_level["D"] + eps)

# Simplicity Index
doc_level["SI"] = (doc_level["N"] + np.abs(doc_level["H"] - doc_level["D"])) / (doc_level["N"] + doc_level["H"] + doc_level["D"] + eps)

# Explanation Index
doc_level["EI"] = np.where(
    (doc_level["H"] + doc_level["D"]) > 0,
    (doc_level["C"] + doc_level["R"] + doc_level["N"]) / (doc_level["H"] + doc_level["D"]),
    np.nan
)
doc_level["EI"] = doc_level["EI"].clip(upper=5)

# Net Confidence Index
doc_level["NCI"] = np.where(
    (doc_level["C"] + doc_level["R"]) > 0,
    (doc_level["C"] - doc_level["R"]) / (doc_level["C"] + doc_level["R"]),
    np.nan
)

# Merge metadata
meta = df[["doc_id", "year_half", "category"]].drop_duplicates()
doc_level = doc_level.merge(meta, on="doc_id", how="left")

# Time aggregation
time_agg = doc_level.groupby("year_half")[["NPS", "SI", "EI", "NCI"]].mean().reset_index()
cat_agg = doc_level.groupby(["category", "year_half"])[["NPS", "SI", "EI", "NCI"]].mean().reset_index()

# Plot NPS and NCI
fig, ax = plt.subplots(figsize=(14, 6))
ax.plot(time_agg["year_half"], time_agg["NPS"], label="NPS (Policy stance)", linewidth=2)
ax.plot(time_agg["year_half"], time_agg["NCI"], label="NCI (Confidence)", linewidth=2)
ax.axhline(0, linestyle="--", color="black", alpha=0.7)
ax.set_title("Central Bank Communication: Policy Stance and Confidence", fontsize=14, fontweight="bold")
ax.set_xlabel("Period")
ax.set_ylabel("Index value")
ax.legend()
ax.grid(True, alpha=0.3)
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("figures/index_nps_nci.png", dpi=300)
plt.show()

# Plot SI and EI
fig, ax = plt.subplots(figsize=(14, 6))
ax.plot(time_agg["year_half"], time_agg["SI"], label="SI (Clarity)", linewidth=2)
ax.plot(time_agg["year_half"], time_agg["EI"], label="EI (Explanation)", linewidth=2)
ax.set_title("Clarity vs Explanation in Central Bank Communication", fontsize=14, fontweight="bold")
ax.set_xlabel("Period")
ax.set_ylabel("Index value")
ax.legend()
ax.grid(True, alpha=0.3)
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("figures/index_si_ei.png", dpi=300)
plt.show()

# Plot NPS by document category
fig, ax = plt.subplots(figsize=(14, 6))
for category in cat_agg["category"].unique():
    subset = cat_agg[cat_agg["category"] == category]
    ax.plot(subset["year_half"], subset["NPS"], label=category)
ax.axhline(0, linestyle="--", color="black")
ax.set_title("Policy Stance by Document Type", fontsize=14, fontweight="bold")
ax.set_xlabel("Period")
ax.set_ylabel("NPS")
ax.legend()
ax.grid(True, alpha=0.3)
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("figures/nps_by_category.png", dpi=300)
plt.show()

# Macroeconomic data processing
GDP_FILE = "GDP_per_quarter.xlsx"
RUONIA_FILE = "RUONIA_rate.xlsx"
RATE_INFL_FILE = "Inflation_and_key_rate.xlsx"
FX_FILE = "Exchange_rate.xlsx"

OUTPUT_XLSX = "macro_monthly_dataset.xlsx"
OUTPUT_CSV = "macro_monthly_dataset.csv"

def clean_numeric_series(s: pd.Series) -> pd.Series:
    """Convert strings like '13 024,8' to float"""
    return (
        s.astype(str)
         .str.replace("\xa0", "", regex=False)
         .str.replace(" ", "", regex=False)
         .str.replace(",", ".", regex=False)
         .replace({"nan": np.nan, "None": np.nan, "": np.nan})
         .astype(float)
    )

def quarter_to_month_end(year: int, quarter_roman: str) -> pd.Timestamp:
    """Convert quarter notation to month end: 'I квартал' -> 03-31"""
    q_map = {"I": 3, "II": 6, "III": 9, "IV": 12}
    month = q_map[quarter_roman]
    return pd.Timestamp(year=year, month=month, day=1) + pd.offsets.MonthEnd(0)

def detect_sheet_by_index_or_name(xlsx_path, preferred_index: int = 2) -> str:
    """Return sheet name, default to 3rd sheet"""
    xl = pd.ExcelFile(xlsx_path)
    if len(xl.sheet_names) > preferred_index:
        return xl.sheet_names[preferred_index]
    return xl.sheet_names[0]

def load_gdp_quarterly(gdp_file, sheet_name: str | None = None) -> pd.DataFrame:
    """Load quarterly GDP data and convert to standardized format"""
    if sheet_name is None:
        sheet_name = detect_sheet_by_index_or_name(gdp_file, preferred_index=2)

    raw = pd.read_excel(gdp_file, sheet_name=sheet_name, header=None)
    raw = raw.dropna(axis=0, how="all").dropna(axis=1, how="all").reset_index(drop=True)

    # Find year row
    year_row_idx = None
    for i in range(min(10, len(raw))):
        row_vals = raw.iloc[i].astype(str).tolist()
        year_count = sum(bool(re.fullmatch(r"\d{4}", v.strip())) for v in row_vals if v.strip() != "nan")
        if year_count >= 2:
            year_row_idx = i
            break

    if year_row_idx is None:
        raise ValueError("Could not find year row in GDP file")

    quarter_row_idx = year_row_idx + 1
    value_row_idx = quarter_row_idx + 1

    years = raw.iloc[year_row_idx].copy().ffill()
    quarters = raw.iloc[quarter_row_idx].copy()
    values = raw.iloc[value_row_idx].copy()

    records = []
    for y, q, v in zip(years, quarters, values):
        if pd.isna(y) or pd.isna(q) or pd.isna(v):
            continue

        y_str = str(y).strip()
        q_str = str(q).strip()

        m = re.match(r"(I{1,3}|IV)\s+квартал", q_str, flags=re.IGNORECASE)
        if not re.fullmatch(r"\d{4}", y_str) or m is None:
            continue

        quarter_roman = m.group(1).upper()
        dt = quarter_to_month_end(int(y_str), quarter_roman)

        records.append({"date": dt, "gdp_real_sa": v})

    if not records:
        raise ValueError("Could not parse quarterly GDP values")

    gdp = pd.DataFrame(records)
    gdp["gdp_real_sa"] = clean_numeric_series(gdp["gdp_real_sa"])
    gdp = gdp.sort_values("date").drop_duplicates("date").reset_index(drop=True)

    # Calculate derivatives
    gdp["gdp_qoq"] = gdp["gdp_real_sa"].pct_change()
    gdp["gdp_yoy"] = gdp["gdp_real_sa"].pct_change(4)

    return gdp

def convert_quarterly_to_monthly_ffill(gdp_q: pd.DataFrame) -> pd.DataFrame:
    """Convert quarterly GDP to monthly using forward fill"""
    monthly_index = pd.date_range(
        start=gdp_q["date"].min().to_period("M").to_timestamp("M"),
        end=gdp_q["date"].max().to_period("M").to_timestamp("M"),
        freq="ME",
    )

    gdp_m = gdp_q.set_index("date").reindex(monthly_index).rename_axis("date").sort_index()
    gdp_m[["gdp_real_sa", "gdp_qoq", "gdp_yoy"]] = gdp_m[["gdp_real_sa", "gdp_qoq", "gdp_yoy"]].ffill()
    gdp_m = gdp_m.reset_index()

    return gdp_m

def load_ruonia_daily(ruonia_file) -> pd.DataFrame:
    """Load daily RUONIA rate data"""
    df = pd.read_excel(ruonia_file)
    df.columns = [str(c).strip() for c in df.columns]

    if "DT" not in df.columns:
        raise ValueError("DT column not found in RUONIA file")

    df["DT"] = pd.to_datetime(df["DT"], dayfirst=True, errors="coerce")

    numeric_cols = ["ruo", "vol", "MinRate", "Percentile25", "Percentile75", "MaxRate"]
    for col in numeric_cols:
        if col in df.columns:
            df[col] = clean_numeric_series(df[col])

    df = df.dropna(subset=["DT"]).sort_values("DT").reset_index(drop=True)
    return df

def aggregate_ruonia_monthly(ruonia_daily: pd.DataFrame) -> pd.DataFrame:
    """Aggregate daily RUONIA to monthly"""
    agg_map = {}
    if "ruo" in ruonia_daily.columns:
        agg_map["ruo"] = ["mean", "last"]
    if "vol" in ruonia_daily.columns:
        agg_map["vol"] = ["mean", "sum"]
    if "MinRate" in ruonia_daily.columns:
        agg_map["MinRate"] = "mean"
    if "Percentile25" in ruonia_daily.columns:
        agg_map["Percentile25"] = "mean"
    if "Percentile75" in ruonia_daily.columns:
        agg_map["Percentile75"] = "mean"
    if "MaxRate" in ruonia_daily.columns:
        agg_map["MaxRate"] = "mean"

    monthly = ruonia_daily.set_index("DT").resample("ME").agg(agg_map)

    monthly.columns = ["_".join([c for c in col if c]).strip("_") if isinstance(col, tuple) else col for col in monthly.columns]
    monthly = monthly.reset_index().rename(columns={"DT": "date"})

    rename_map = {
        "ruo_mean": "ruonia_mean",
        "ruo_last": "ruonia_last",
        "vol_mean": "ruonia_volume_mean",
        "vol_sum": "ruonia_volume_sum",
    }
    monthly = monthly.rename(columns=rename_map)

    return monthly

def load_rate_inflation_monthly(rate_infl_file) -> pd.DataFrame:
    """Load monthly key rate and inflation data"""
    df = pd.read_excel(rate_infl_file)
    df.columns = [str(c).strip() for c in df.columns]

    date_col = None
    for c in df.columns:
        if "дата" in c.lower():
            date_col = c
            break
    if date_col is None:
        raise ValueError("Date column not found in rate/inflation file")

    rate_col = next((c for c in df.columns if "ключевая" in c.lower()), None)
    infl_col = next((c for c in df.columns if "инфляц" in c.lower()), None)
    target_col = next((c for c in df.columns if "цель" in c.lower()), None)

    if rate_col is None or infl_col is None:
        raise ValueError("Key rate or inflation columns not found")

    df["date"] = pd.to_datetime("01." + df[date_col].astype(str), format="%d.%m.%Y", errors="coerce")
    df["date"] = df["date"] + pd.offsets.MonthEnd(0)

    df["key_rate"] = clean_numeric_series(df[rate_col])
    df["inflation_yoy"] = clean_numeric_series(df[infl_col])

    if target_col is not None:
        df["inflation_target"] = clean_numeric_series(df[target_col])
    else:
        df["inflation_target"] = np.nan

    out = df[["date", "key_rate", "inflation_yoy", "inflation_target"]].dropna(subset=["date"])
    out = out.sort_values("date").drop_duplicates("date").reset_index(drop=True)

    return out

def load_fx_daily(fx_file) -> pd.DataFrame:
    """Load daily exchange rate data"""
    df = pd.read_excel(fx_file)
    df.columns = [str(c).strip() for c in df.columns]

    date_col = next((c for c in df.columns if c.lower() in {"data", "date"}), None)
    rate_col = next((c for c in df.columns if "curs" in c.lower()), None)
    cdx_col = next((c for c in df.columns if "cdx" in c.lower()), None)

    if date_col is None or rate_col is None:
        raise ValueError("Date or rate column not found in FX file")

    df[date_col] = pd.to_datetime(df[date_col], dayfirst=True, errors="coerce")
    df[rate_col] = clean_numeric_series(df[rate_col])

    # Filter for USD if multiple currencies present
    if cdx_col is not None:
        mask = df[cdx_col].astype(str).str.contains("доллар", case=False, na=False)
        if mask.any():
            df = df.loc[mask].copy()

    out = df[[date_col, rate_col]].rename(columns={date_col: "date", rate_col: "usd_rub"})
    out = out.dropna(subset=["date", "usd_rub"]).sort_values("date").reset_index(drop=True)

    return out

def aggregate_fx_monthly(fx_daily: pd.DataFrame) -> pd.DataFrame:
    """Aggregate daily FX to monthly"""
    monthly = (
        fx_daily.set_index("date")
        .resample("ME")
        .agg(
            usd_rub_mean=("usd_rub", "mean"),
            usd_rub_last=("usd_rub", "last"),
            usd_rub_min=("usd_rub", "min"),
            usd_rub_max=("usd_rub", "max"),
        )
        .reset_index()
    )
    return monthly

def build_macro_dataset(gdp_file, ruonia_file, rate_infl_file, fx_file) -> tuple[pd.DataFrame, dict]:
    """Build comprehensive monthly macroeconomic dataset"""
    # Load individual datasets
    gdp_q = load_gdp_quarterly(gdp_file)
    gdp_m = convert_quarterly_to_monthly_ffill(gdp_q)
    ruonia_daily = load_ruonia_daily(ruonia_file)
    ruonia_m = aggregate_ruonia_monthly(ruonia_daily)
    rate_infl_m = load_rate_inflation_monthly(rate_infl_file)
    fx_daily = load_fx_daily(fx_file)
    fx_m = aggregate_fx_monthly(fx_daily)

    # Create common monthly index
    start_date = min(x["date"].min() for x in [gdp_m, ruonia_m, rate_infl_m, fx_m] if not x.empty)
    end_date = max(x["date"].max() for x in [gdp_m, ruonia_m, rate_infl_m, fx_m] if not x.empty)

    base = pd.DataFrame({"date": pd.date_range(start_date, end_date, freq="ME")})

    # Merge all datasets
    final = (
        base.merge(gdp_m, on="date", how="left")
            .merge(ruonia_m, on="date", how="left")
            .merge(rate_infl_m, on="date", how="left")
            .merge(fx_m, on="date", how="left")
            .sort_values("date")
            .reset_index(drop=True)
    )

    # Forward fill quarterly GDP
    for col in ["gdp_real_sa", "gdp_qoq", "gdp_yoy"]:
        if col in final.columns:
            final[col] = final[col].ffill()

    # Calculate derived features
    if "usd_rub_last" in final.columns:
        final["usd_rub_mom"] = final["usd_rub_last"].pct_change()
        final["usd_rub_yoy"] = final["usd_rub_last"].pct_change(12)

    if "ruonia_mean" in final.columns and "key_rate" in final.columns:
        final["ruonia_key_spread"] = final["ruonia_mean"] - final["key_rate"]

    if "inflation_yoy" in final.columns and "inflation_target" in final.columns:
        final["inflation_gap"] = final["inflation_yoy"] - final["inflation_target"]

    if "key_rate" in final.columns and "inflation_yoy" in final.columns:
        final["real_key_rate_ex_post"] = final["key_rate"] - final["inflation_yoy"]

    # Add lags for regression analysis
    lag_cols = ["key_rate", "inflation_yoy", "inflation_gap", "ruonia_mean", "usd_rub_last", "gdp_real_sa", "gdp_qoq", "gdp_yoy"]
    for col in lag_cols:
        if col in final.columns:
            final[f"{col}_lag1"] = final[col].shift(1)

    # Filter from Feb 2014 onwards
    cutoff_date = pd.Timestamp("2014-02-14")
    final = final[final["date"] >= cutoff_date].copy()
    final = final.reset_index(drop=True)

    meta = {
        "gdp_quarterly": gdp_q,
        "gdp_monthly": gdp_m,
        "ruonia_daily": ruonia_daily,
        "ruonia_monthly": ruonia_m,
        "rate_infl_monthly": rate_infl_m,
        "fx_daily": fx_daily,
        "fx_monthly": fx_m,
    }

    return final, meta

# Build macro dataset
final_df, meta = build_macro_dataset(
    gdp_file=GDP_FILE,
    ruonia_file=RUONIA_FILE,
    rate_infl_file=RATE_INFL_FILE,
    fx_file=FX_FILE,
)

final_df.to_excel(OUTPUT_XLSX, index=False)
final_df.to_csv(OUTPUT_CSV, index=False, encoding="utf-8-sig")

# Prepare macro subset for analysis
cols = ["date", "key_rate", "inflation_yoy", "ruonia_mean", "usd_rub_last", "gdp_qoq"]
df_small = final_df[cols].copy()

# Align sentiment data with macro
df["published_date"] = pd.to_datetime(df["published_date"])
df["date"] = df["published_date"].dt.to_period("M").dt.to_timestamp("M")
df["net_hawkish"] = df["sentiment_hawkish"].fillna(0) - df["sentiment_dovish"].fillna(0)

sent_monthly = df.groupby("date").agg({"net_hawkish": "mean", "forward_lookingness": "mean"}).reset_index()

df_small["date"] = pd.to_datetime(df_small["date"])
data = df_small.merge(sent_monthly, on="date", how="inner")
data = data.sort_values("date")

# Fill missing values
data["key_rate_filled"] = data["key_rate"].ffill()
infl_nan = data["inflation_yoy"].isna()

# Plot key rate and inflation
plt.figure(figsize=(12, 6))
plt.plot(data["date"], data["key_rate_filled"], label="Key rate", linewidth=2)
plt.plot(data["date"], data["inflation_yoy"], label="Inflation", linestyle="--")

for i in range(len(data)):
    if infl_nan.iloc[i]:
        plt.axvspan(data["date"].iloc[i], data["date"].iloc[i], color="gray", alpha=0.3)

plt.title("Key Rate and Inflation (missing inflation data highlighted)")
plt.legend()
plt.grid(True)
plt.savefig("figures/key_rate_inflation.png", dpi=150, bbox_inches='tight')
plt.show()

# Normalize function for comparison
def norm(x):
    return (x - x.mean()) / x.std()

# Smooth sentiment with rolling average
data["sent_smooth"] = data["net_hawkish"].rolling(window=3, min_periods=1, center=True).mean()

# Plot smoothed sentiment vs key rate
plt.figure(figsize=(12, 6))
plt.plot(data["date"], norm(data["sent_smooth"]), label="Smoothed sentiment")
plt.plot(data["date"], norm(data["key_rate_filled"]), label="Key rate")
plt.legend()
plt.grid(True)
plt.title("Smoothed sentiment vs Key rate")
plt.savefig("figures/sentiment_vs_keyrate.png", dpi=150, bbox_inches='tight')
plt.show()

# Plot inflation and sentiment
plt.figure(figsize=(12, 6))
plt.plot(data["date"], norm(data["inflation_yoy"]), label="Inflation (normalized)", linewidth=2)
plt.plot(data["date"], norm(data["sent_smooth"]), label="Smoothed sentiment (normalized)", linestyle="--", linewidth=2)
plt.title("Inflation and Sentiment")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# Plot overall macro and sentiment
plt.figure(figsize=(12, 6))
plt.plot(data["date"], norm(data["inflation_yoy"]), label="Inflation (normalized)", linewidth=2)
plt.plot(data["date"], norm(data["key_rate"].ffill()), label="Key rate (normalized)", linewidth=2)
plt.plot(data["date"], norm(data["sent_smooth"]), label="Smoothed sentiment (normalized)", linestyle="--", linewidth=2)
plt.title("Inflation, Key Rate, and Sentiment")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig("figures/overall_macro_sentiment.png", dpi=150, bbox_inches='tight')
plt.show()